spring:
  profiles:
    active: local
---
spring:
  config:
    activate:
      on-profile:
        - local

  data:
    mongodb:
      host: localhost
      port: 27017
      database: local

server:
  port: 8480
---
spring:
  config:
    activate:
      on-profile:
        - prod

  data:
    mongodb:
      host: localhost
      port: 27017
      database: local
---
spring:
  config:
    activate:
      on-profile: test

  mongodb:
    embedded:
      version: latest

  data:
    mongodb:
      port: 0