version: '3.8'

services:
  database:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: reactivedb
      MONGO_INITDB_ROOT_PASSWORD: reactivedb
    labels:
      org.springframework.boot.readiness-check.tcp.disable: true

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - database
    ports:
      - 8881:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: reactivedb
      ME_CONFIG_MONGODB_ADMINPASSWORD: reactivedb
      ME_CONFIG_MONGODB_SERVER: database