server:
  port: 8085

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: reactivedb

  thymeleaf:
    reactive:
      max-chunk-size: 1024

  webflux:
    hiddenmethod:
      filter:
        enabled: true